
name: PUSH Staging Workflow

on:
  push:
    branches:
      - staging

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_STAGING_PASSWORD }}
          MYSQL_DATABASE: authmicroservice
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_STAGING_PASSWORD }}
          DB_DATABASE: authmicroservice
        run: |
          php artisan migrate --seeder
          php artisan test
      - name: Generate Documentation
        run: php artisan scribe:generate
  deploy-staging:
    name: Deploy Project to STAGING Server
    runs-on: ubuntu-latest
    needs: [app-tests]
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Documentation
        run: php artisan scribe:generate
      - name: Copy Documentation To Public Folder
        run: |
          php -r "file_exists('storage/app/scribe/openapi.yaml') || copy('storage/app/scribe/openapi.yaml', 'public/vendor/scribe/openapi.yaml');"
          php -r "file_exists('storage/app/scribe/collection.json') || copy('storage/app/scribe/collection.json', 'public/vendor/scribe/collection.json');"
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to Staging
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        run: dep deploy env=staging --tag=${{ env.GITHUB_REF }} -vvv

